# Generated by Django 5.1.3 on 2024-11-11 00:29

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('Ju', 'jueves'), ('Ma', 'martes'), ('Lu', 'lunes'), ('Mi', 'miercoles'), ('Vi', 'Viernes'), ('Do', 'Domingo'), ('Sa', 'Sabado')], max_length=20)),
                ('inicio_primero', models.TimeField()),
                ('fin_primero', models.TimeField()),
                ('inicio_segundo', models.TimeField()),
                ('fin_segundo', models.TimeField()),
                ('photo', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
