# Generated by Django 5.1.3 on 2024-11-11 02:33

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mi', 'miercoles'), ('Vi', 'Viernes'), ('Sa', 'Sabado'), ('Ju', 'jueves'), ('Do', 'Domingo'), ('Lu', 'lunes'), ('Ma', 'martes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='fin_segundo',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='inicio_segundo',
            field=models.TimeField(blank=True),
        ),
    ]
