# Generated by Django 5.1.3 on 2024-11-11 02:37

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_days_alter_restaurant_fin_segundo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Vi', 'Viernes'), ('Lu', 'lunes'), ('Do', 'Domingo'), ('Mi', 'miercoles'), ('Ma', 'martes'), ('Sa', 'Sabado'), ('Ju', 'jueves')], max_length=20),
        ),
    ]
