# Generated by Django 5.1.3 on 2024-11-11 03:09

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_days_jobs_restaurant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='days_jobs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ma', 'martes'), ('mi', 'miercoles'), ('vi', 'viernes'), ('lu', 'lunes'), ('do', 'domingo'), ('ju', 'jueves'), ('sa', 'sabado')], default='domingo', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='fin_segundo',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='inicio_segundo',
            field=models.TimeField(default=None),
        ),
    ]
