# Generated by Django 5.1.3 on 2024-11-11 03:13

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurant_days_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='days_jobs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lu', 'lunes'), ('sa', 'sabado'), ('do', 'domingo'), ('mi', 'miercoles'), ('vi', 'viernes'), ('ju', 'jueves'), ('ma', 'martes')], default='domingo', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='fin_segundo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='inicio_segundo',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
