# Generated by Django 5.1.3 on 2024-11-11 03:24

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_restaurant_days_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='days_jobs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mi', 'miercoles'), ('lu', 'lunes'), ('ju', 'jueves'), ('vi', 'viernes'), ('ma', 'martes'), ('sa', 'sabado'), ('do', 'domingo')], default='domingo', max_length=20),
        ),
    ]
