# Generated by Django 5.1.3 on 2024-11-12 23:31

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_restaurant_days_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='days_jobs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ma', 'martes'), ('lu', 'lunes'), ('do', 'domingo'), ('ju', 'jueves'), ('vi', 'viernes'), ('sa', 'sabado'), ('mi', 'miercoles')], default='domingo', max_length=20),
        ),
    ]
