# Generated by Django 5.1.3 on 2024-11-12 23:41

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_restaurant_days_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='days_jobs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('do', 'domingo'), ('mi', 'miercoles'), ('ju', 'jueves'), ('vi', 'viernes'), ('ma', 'martes'), ('lu', 'lunes'), ('sa', 'sabado')], default='domingo', max_length=20),
        ),
    ]
